### ISSUE TITLE
B715S-23C

### ISSUE THREAD

**Issue by jeromecandau** [aalteirac/router_monitor#2]
Hi. Your API for B715S-23C Huawei seems to be very well designed. As I want to use such a model to send SMS, but in PHP, I tried to find documentation but I didn't. Have you such documents wich could help me ? Thanks and best regards.
Jerome CANDAU

**Comment by aalteirac** [comment]
Hey Jerome, 

It's pure reverse-engineering on the web app provided with the router :-/ Not super complex, just sniff the rest api calls and you're good to go :-) 

Hope it helps
